name: Workflow in Repo1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: trigger
        run: |
          echo "doing some stuff..."
          repository: 88lambda/test3
          token: ${{ secrets.TOKEN }}
          event-type: trigger-workflow
          client-payload: '{"ref": "${{ github.ref }}"}'
          echo "stuff done"
